### ISSUE TITLE
Logging: Implement timing_error in bubble_pop events

### ISSUE THREAD

**Issue by LswaN58** [fielddaylab/penguinsVR#1]
Currently, the `bubble_pop` event includes an `event_data` member named `timing`.

This should be renamed to `timing_error`, and hold a float value between -0.5 and 0.5.
This value should be the number of seconds before or after the "BEAT" when the ring reaches a bubble and causes the bubble to glow.
There is a half-second window before and after the "BEAT" when the bubble can be popped; thus, the number of seconds naturally corresponds to a [-0.5, 0.5] range of values. Negative values are for popping before the "BEAT", and positive for after.

**Comment by rossTnick** [comment]
This should be in the latest build on alpha channel.

**Comment by rossTnick** [comment]
052aaf5e96afbb55acd00a0145697ddb8c8d6ea7
