### ISSUE TITLE
gaze_object_begin and gaze_object_end are wildly inconsistent

### ISSUE THREAD

**Issue by LswaN58** [fielddaylab/penguinsVR#10]
Begin events and end events do not pair nicely. We see many "begin" events on a single object, then a single "end", and perhaps later we see many "end" events for that object, without more "begin" events in between.

**Comment by yqxiao28** [comment]
[Penguin Data Section](https://docs.google.com/spreadsheets/d/1PFnHsSB295DfftWHJHk-TrurpJPYJx_YZsvA1DzeFwU/edit?usp=sharing)

We are trying to capture the duration between each gazing action.This is a section of the `gaze_object_begin/end` event data which I found both `gaze begin`and `gaze end`  appears multiple times on the same object but the `begin` and `end` don't appear to be in pairs. 

![image](https://user-images.githubusercontent.com/40223724/221291173-bc877994-8ba6-45dd-9685-324426c3d3be.png)

This is a screen shot of the `gaze_object_begin/end` count feature which capture the number of `gaze_object_begin` in index 0 and 'gaze_object_end` in index 1 of each object. From this screen shot we can also see the number of time `begin` and `end` object appeared in different numbers.

**Comment by yqxiao28** [comment]
[Penguin Data Section](https://docs.google.com/spreadsheets/d/1PFnHsSB295DfftWHJHk-TrurpJPYJx_YZsvA1DzeFwU/edit?usp=sharing)

We are trying to capture the duration between each gazing action.This is a section of the `gaze_object_begin/end` event data which I found both `gaze begin`and `gaze end`  appears multiple times on the same object but the `begin` and `end` don't appear to be in pairs. 

![image](https://user-images.githubusercontent.com/40223724/221291173-bc877994-8ba6-45dd-9685-324426c3d3be.png)

This is a screen shot of the `gaze_object_begin/end` count feature which capture the number of `gaze_object_begin` in index 0 and 'gaze_object_end` in index 1 of each object. From this screen shot we can also see the number of time `begin` and `end` object appeared in different numbers

**Comment by LswaN58** [comment]
Previously closed by mistake.

**Comment by rossTnick** [comment]
6ffcf92
