### ISSUE TITLE
Malformed JSON string in `right_hand_data` events.

### ISSUE THREAD

**Issue by LswaN58** [fielddaylab/penguinsVR#13]
## NOTE: This has the same description as for the `viewport_data` case, just tracking separately so we make sure all similarly-formatted events get updated.

The JSON string in the `right_hand_data_package` element of the event_data column is badly formatted.

Currently, its form is something like:
`"gaze_data_package" : "`  
`     {\"pos\":\"3.163,3.631,58.913\",\"rot\":\"0.025,0.604,0.000,0.797\"}  `  
`    {\"pos\":\"3.163,3.631,58.914\",\"rot\":\"0.025,0.600,0.001,0.799\"},`  
`     ...                                                                   `  
`    {\"pos\":\"3.162,3.631,58.906\",\"rot\":\"0.025,0.612,-0.001,0.791\"}`
`"`

As we can see here, the sub-dictionaries are meant to be in a list, but the string lacks surrounding `[` and `]` brackets to make them a list. Further, there are no commas separating the sub-dicts.

In addition, the values are given as a comma-separated string. We can actually save a couple characters *and* make JSON parsing nicer if we instead format them as lists of numbers,  
e.g. convert `\"pos\":\"3.163,3.631,58.913\"` to `\"pos\":[3.163,3.631,58.913]`

Thus, the new JSON string format should be made to look like:
`"gaze_data_package" : "[`  
`    {\"pos\":[3.163,3.631,58.913],\"rot\":[0.025,0.604,0.000,0.797]},`  
`    {\"pos\":[3.163,3.631,58.914],\"rot\":[0.025,0.600,0.001,0.799]},`  
`     ...                                                               `  
`    {\"pos\":[3.162,3.631,58.906],\"rot\":[0.025,0.612,-0.001,0.791]}`  
`]"`

**Comment by rossTnick** [comment]
0b85669
