### ISSUE TITLE
Update map "regions" due to new activities

### ISSUE THREAD

**Issue by LswaN58** [fielddaylab/penguinsVR#19]
When we originally created the "region" bounding boxes in the game (for logging events `enter_region` and `exit_region`), the regions were defined for the activities that existed at the time. We need to update the set of regions based on the many changes to activities (i.e. removing bowling, bubble popping, and chimes, which are replaced with nest-building and dancing).

The regions now should be:

* `"MIRROR"` : Previously there were separate regions for "entrance" and "mirror," but we can just have one combined `"MIRROR"` region for the entrance area, where players are expected to stop and look in the mirror.
* `"HILL"` : Previously there were separate regions for "HillUp" and "HillDown," but we can just have one combined `"HILL"` region.
* `"NEST"` : This will be the area containing all the rocks and nests (including other penguins' nests)
* `"BRIDGE"` : This can be the same as before.
* `"MATING_DANCE"` : The area where penguins are performing mating dances (I'm not sure if other penguins do mating dances or not, but if so the region should include them).
* `"EGG_DEFENSE"` : The area where skuas fly around while the player defends their egg.

These bounding boxes should be created, and their minimum X, Y, Z, and maximum X, Y, Z should be reported back to the data team.

**Comment by rossTnick** [comment]
7c7feb65b3209f58b629bcaf5ed91a36c1a7038f
The region bounds json file has been checked into the penguinsVR/Assets directory - region_bounds.txt
