### ISSUE TITLE
Logging: rename a couple egg events

### ISSUE THREAD

**Issue by LswaN58** [fielddaylab/penguinsVR#2]
In the event writeup, we have events `egg_hatched`, `lost_egg`, and `recover_egg` as feedback events. For consistency, let's go with noun-verb as the format for all three of these, so we have:

`egg_hatched`, `egg_lost`, and `egg_recovered`.

**Comment by rossTnick** [comment]
4c7b677fdf1facdaf87022dcb57e4a57aa72ed33
