### ISSUE TITLE
Logging: Verify `activity_begin` event

### ISSUE THREAD

**Issue by LswaN58** [fielddaylab/penguinsVR#20]
It appears the activity begin and end events have been updated for the current set of activities (skuas, nest, mating_dance). 

We just need to verify that these begin on the right events:
* `nest` : should begin when the player picks up a rock for the first time
* `mating_dance` : should begin when the game triggers the dance, locking the player so that swaying their head counts as "dancing" instead of "waddling"
* `skuas` : should begin when the game triggers the skua activity, putting the player in the middle of the nest area (assuming it teleports the player there - I don't recall for certain).

I'm guessing this is already how these are set up, but it's possible we were using enter/exit of regions to trigger this before, so we need to verify and document it.

Please let me know when this has been checked and we know the moments above are when the `activity_begin` event will fire.

**Comment by rossTnick** [comment]
This was double checked and is true to the description above.
