### ISSUE TITLE
Logging: Update `gaze_object_begin` and `gaze_object_end` events

### ISSUE THREAD

**Issue by LswaN58** [fielddaylab/penguinsVR#21]
### First, the bug

`gaze_object_end` events **vastly** outnumber `gaze_object_begin` events.
It's unclear why this happens, but our current best guess is that `gaze_object_begin` is checking only the first object intersecting the gaze vector, while the `gaze_object_end` event is firing for any object intersecting the gaze vector, even if not the nearest.

We would like the behavior of both events to only trigger for the nearest object. That is, we should be keeping track only of the first/nearest object intersecting the gaze vector; when a given object remains first for at least 0.25 of a second, we log `gaze_object_begin`, and then we log a corresponding `gaze_object_end` as soon as the gaze vector has some other object as the nearest intersection.

In that way, every `begin` should pair with an `end` event, and it should be at least 0.25 before some other object can trigger a `begin` event.

### Second, the enhancement

There are certain items we want to see as "objects" that can trigger the `gaze_object_begin`/`_end` events. These are:

* Tents
* The mirror
* Signs
* The guide penguin
* Other penguins (assuming each has a number/ID we can use)

Some of these currently exist in the log data, but I don't necessarily see all of them. We need to ensure all of these can be logged for `gaze_object_begin` and `_end`.
Others that are currently being logged, such as `Sea#` and `River#`, aren't really needed, although if leaving them in place does not break anything, there's no problem in continuing to include those.
We just need to ensure the specific items mentioned above *are* included.

**Comment by rossTnick** [comment]
7c7feb65b3209f58b629bcaf5ed91a36c1a7038f
