### ISSUE TITLE
Logging: New event - `place_rock`

### ISSUE THREAD

**Issue by LswaN58** [fielddaylab/penguinsVR#22]
We currently have an event for `nest_complete` (or some similar name).
However, we don't yet have an event for all the rocks added prior to finishing the nest.

Add a new event, whose `event_name` is `"place_rock"`, and has the following elements in the `event_data`:

* `rock_count` : The total number of rocks that have been placed on the nest so far, including the one that is placed in the event.
* `percent_complete` : The proportion (i.e. from 0 to 1) of completion of the nest after the new rock has been added. Since nests currently take 4 rocks to complete, we'd expect a value of 0.25 after the first rock is placed, then 0.5, 0.75, and 1.00 when the nest gets completed.

**Comment by rossTnick** [comment]
7c7feb65b3209f58b629bcaf5ed91a36c1a7038f
