### ISSUE TITLE
Logging: New events - `stand_on_rock` and `stand_on_nest`

### ISSUE THREAD

**Issue by LswaN58** [fielddaylab/penguinsVR#23]
These events should occur when the player avatar's feet intersect a nest or rock object for at least 0.25 seconds.
This should apply for any nest (not just the player nest).
Also, to be specific, by "rock" we mean the rocks players can pick up and put in the nest, not rocks that are just part of the environment.

The `stand_on_rock` event should have the following elements in its `event_data`:

* `rock_id` : Assuming each rock has an identifier, such as a name or index, it should be logged here. If there is no individual ID for rocks, tell Luke so it can be documented.
* `rock_pos` : The x, y, z coordinates of the rock, as a 3-item list (similar to the format used in `viewport_data` or `right_hand_data` packets)

The `stand_on_nest` event should have the following elements in its `event_data`:

* `nest_id` : Same idea as for `rock_id`. If there is no individual ID for nests, tell Luke so it can be documented.
* `nest_pos` : Same idea as for `rock_pos`.

**Comment by rossTnick** [comment]
7c7feb65b3209f58b629bcaf5ed91a36c1a7038f
