### ISSUE TITLE
Logging: New events - `peck_rock`, `peck_nest`, `peck_penguin`, `peck_skua`

### ISSUE THREAD

**Issue by LswaN58** [fielddaylab/penguinsVR#24]
## Summary

Currently, the game (we assume) checks for collisions between the player's beak and the rocks in the nest-building area to determine when a player "picks up" a rock.
We would like to expand this logic, to check for *any* time the player's beak intersects a rock, nest, other penguin, or skua (such as the case where a player mistakenly tries to "peck" a skua instead of doing a flipper-bash).

This event should be triggered and logged even if the collision does not have any effect in the game. For example, if the player has already picked up a rock, and tries to pick up another rock, there should be a `peck_rock` in *both* cases.
Note also that `peck_rock` should be logged in addition to the existing `pickup_rock`. That is, when a player successfully picks up a rock, we should see both a `peck_rock` and `pickup_rock`; when they try to pick up a rock while already carrying a rock, we should see only the `peck_rock` without a `pickup_rock`.

### `peck_rock`

The `peck_rock` event should have the following elements in its `event_data`:

* `rock_id` : Assuming each rock has its own ID (such as an object name or an index), this should be logged. If rocks do not have unique IDs of some kind, tell Luke so this can be documented.
* `rock_pos` : The x, y, and z coordinates of the rock object, as a 3-item list, similar to the format used for individual frames in `viewport_data` or `right_hand_data`

### `peck_nest`

The `peck_nest` event should have the following elements in its `event_data`:

* `nest_id` : Same idea as `rock_id`. If nests do not have unique IDs of some kind, tell Luke so this can be documented. At minimum, we should be able to log this as `"PLAYER_NEST"` or `"NORMAL"` to indicate whether the pecked nest was the player's nest or some other penguin's nest.
* `nest_pos` : Same idea as `rock_pos`

### `peck_penguin`

The `peck_penguin` event should have the following elements in its `event_data`:

* `penguin_id` : Same idea as `rock_id`. If penguins do not have unique IDs of some kind, tell Luke so this can be documented. At minimum, we should be able to log this as `"GUIDE"` or `"NORMAL"` to indicate whether the pecked penguin was the guide or some other penguin.
* `penguin_pos` : Same idea as `rock_pos`

### `peck_skua`

The `peck_skua` event should have the following elements in its `event_data`:

* `skua_id` : Same idea as `rock_id`. If skuas do not have unique IDs of some kind, tell Luke so this can be documented.
* `skua_pos` : Same idea as `rock_pos`

**Comment by rossTnick** [comment]
7c7feb65b3209f58b629bcaf5ed91a36c1a7038f
