### ISSUE TITLE
Logging: New events - `flipper_bash_rock`, `flipper_bash_nest`, `flipper_bash_penguin`, `flipper_bash_skua`

### ISSUE THREAD

**Issue by LswaN58** [fielddaylab/penguinsVR#25]
## Summary

Currently, the game (we assume) checks for collisions between the player's flippers and the skuas in the egg-defense area to determine when a player "bashes" a skua.
We would like to expand this logic, to check for any time the player's flipper intersects a rock, nest, or other penguin.

This event should be triggered and logged even though these collisions do not have any effect in the game.
Note, since `flipper_bash_skua` already exists, it's not actually a "new event" here. **However**, we *are* going to change the `event_data` in the `flipper_bash_skua` event.

### `flipper_bash_rock`

The `flipper_bash_rock` event should have the following elements in its `event_data`

* `rock_id` : Assuming each rock has its own ID (such as an object name or an index), this should be logged. If rocks do not have unique IDs of some kind, tell Luke so this can be documented.
* `rock_pos` : The x, y, and z coordinates of the rock object, as a 3-item list, similar to the format used for individual frames in viewport_data or right_hand_data
* `hand` : Either `"RIGHT"` or `"LEFT"`, indicating whether the player used their right or left flipper to bash the rock.

### `flipper_bash_nest`

The `flipper_bash_nest` event should have the following elements in its `event_data`

* `nest_id` : Same idea as `rock_id`. If nests do not have unique IDs of some kind, tell Luke so this can be documented. At minimum, we should be able to log this as `"PLAYER_NEST"` or `"NORMAL"` to indicate whether the bashed nest was the player's nest or some other penguin's nest.
* `nest_pos` : Same idea as `rock_pos`
* `hand` : Same idea as `hand` in the `flipper_rock` case

### `flipper_bash_penguin`

The `flipper_bash_penguin` event should have the following elements in its event_data

* `penguin_id` : Same idea as `rock_id`. If penguins do not have unique IDs of some kind, tell Luke so this can be documented. At minimum, we should be able to log this as `"GUIDE"` or `"NORMAL"` to indicate whether the bashed penguin was the guide or some other penguin.
* `penguin_pos` : Same idea as `rock_pos`

### `flipper_bash_skua`

The `flipper_bash_skua` event should _**be updated**_ to have the following elements in its `event_data`:

* `skua_id` : Same idea as `rock_id`. Currently this is called `object_id`, but we should rename to the more-meaningful `skua_id`.
* `skua_pos` : Same idea as `rock_pos`
* `penguin_pos` : Same idea as `rock_pos`

**Comment by rossTnick** [comment]
7c7feb65b3209f58b629bcaf5ed91a36c1a7038f

**Comment by LswaN58** [comment]
I just discovered a few mistakes I made, specifically for `flipper_bash_penguin` and `flipper_bash_skua`. In both cases, I forgot to include a `hand` element. In the case of `flipper_bash_skua`, I also included a redundant `penguin_pos`. Let's make one more tweak to get these corrected. The **corrected** data should look like:

### `flipper_bash_penguin`

The `flipper_bash_penguin` event should have the following elements in its event_data

* `penguin_id` : Same idea as `rock_id`. If penguins do not have unique IDs of some kind, tell Luke so this can be documented. At minimum, we should be able to log this as `"GUIDE"` or `"NORMAL"` to indicate whether the bashed penguin was the guide or some other penguin.
* `penguin_pos` : Same idea as `rock_pos`
* `hand` : Either `"RIGHT"` or `"LEFT"`, indicating whether the player used their right or left flipper to bash the rock.

### `flipper_bash_skua`

The `flipper_bash_skua` event should _**be updated**_ to have the following elements in its `event_data`:

* `skua_id` : Same idea as `rock_id`. Currently this is called `object_id`, but we should rename to the more-meaningful `skua_id`.
* `skua_pos` : Same idea as `rock_pos`
* `hand` : Same idea as `hand` in the `flipper_bash_penguin` case

**Comment by rossTnick** [comment]
4334b4e4ebb7626817f6f46eaf29cb4e5f786a51
