### ISSUE TITLE
Logging: Adjust `game_state` pos/rot format

### ISSUE THREAD

**Issue by LswaN58** [fielddaylab/penguinsVR#26]
Currently, in the `viewport_data`, `right_hand_data`, etc. we have all position and rotation data given as arrays of 3 or 4 floats, e.g. `[x, y, z]` for position. However, the `game_state` currently has individual items for each position/rotation component, e.g. `pos_x`, `pos_y`, `pos_z` for position.

We'd like to make these consistent, so the `game_state` should be updated to just have `pos` and `rot`, where `pos` has format `[x, y, z]` and `rot` has format `[x, y, z, w]`.

Then the overall form of the game_state for each event in Penguins should be like:

```
{
    "pos" : [x, y, z],
    "rot" : [x, y, z, w],
    "seconds_from_launch" : 1.234
}
```

**Comment by rossTnick** [comment]
7c7feb65b3209f58b629bcaf5ed91a36c1a7038f
