### ISSUE TITLE
Logging: Adjust `player_waddle` pos/rot format

### ISSUE THREAD

**Issue by LswaN58** [fielddaylab/penguinsVR#27]
Currently, in the `viewport_data`, `right_hand_data`, etc. we have all position and rotation data given as arrays of 3 or 4 floats, e.g. `[x, y, z]` for position. However, the `player_waddle` currently has individual items for each position/rotation component, e.g. `old_posX`, `old_posY`, `old_posZ` for player's previous position.

Additionally, we were kind of fuzzy on which part of the player's position and rotation were being captured. On further thought, we would like to use the position of the player's feet. That way, if we were to chart the positions overlaid on a map, we'd essentially see the overlay as a bunch of spots on the ground, rather than floating in air.

Finally, we want to remove the rotation components from `event_data` for the `player_waddle` events, since rotation is contained in `game_state` already, and does not change as a result of the waddle.

Thus, the updated set of items in the `event_data` for `player_waddle` should be:

* `object_id` : same as before
* `pos_old` : the position of the player avatar's _feet_ just before they were teleported by the waddle, in the form `[x, y, z]`
* `pos_new` : the position of the player avatar's _feet_, after they were teleported by the waddle, in the form `[x, y, z]`

**Comment by rossTnick** [comment]
7c7feb65b3209f58b629bcaf5ed91a36c1a7038f
