### ISSUE TITLE
On initialization of game, set Unity's random seed = session ID

### ISSUE THREAD

**Issue by LswaN58** [fielddaylab/penguinsVR#28]
For our game replay project, we need to know the seed used for any randomization of the game.
In order to keep an illusion of randomness, we'd like to use the `session_id` for each gameplay session to set the random seed.

This way, we have a systematic, predictable way to set the seed, allowing us to accurately replay a session, but also avoid players having the same random seed each time they play.

Note: if needed, we could use something like the last `n` digits of the `session_id`, or take `session_id % MAX_INT` or whatever, as long as the actual seed used is easily calculated from the `session_id`

**Comment by rossTnick** [comment]
7c7feb65b3209f58b629bcaf5ed91a36c1a7038f
