### ISSUE TITLE
Logging: Include `random_seed` in `application_start`

### ISSUE THREAD

**Issue by LswaN58** [fielddaylab/penguinsVR#29]
This issue is somewhat tied to issue #28, where we will set the random seed to match the session ID.
We want to include the random seed in logging in case the choice of seed ever differs from session ID (e.g. in case we need to do something to shorten from the ID to a valid int size or similar).

In any case, we would like to include the random seed in the initial `application_begin` event, which I assume is being sent once everything is initialized, e.g. the player has been assigned a session ID and the random seed has been set.

Then the `event_data` for the `application_begin` event should be:
* `"random_seed"` : The random seed used for all random number/position/rotation generation in the game.

**Comment by rossTnick** [comment]
7c7feb65b3209f58b629bcaf5ed91a36c1a7038f
