### ISSUE TITLE
Logging: Rename mating_dance_complete_indicator_

### ISSUE THREAD

**Issue by LswaN58** [fielddaylab/penguinsVR#3]
So, the original penguin event doc had a ridiculously long name for the event, and it looks like this got cut off in the database by the column width (32 chars). Using a name so long it practically needs a paragraph break isn't great.

Let's rename this event just to `mating_dance_indicator_updated`. This is just 30 characters, and gets all the important bits of the original name.

**Comment by rossTnick** [comment]
4c7b677fdf1facdaf87022dcb57e4a57aa72ed33
