### ISSUE TITLE
Logging: Rename `application_start` -> `session_start` and `begin` -> `game_start`

### ISSUE THREAD

**Issue by LswaN58** [fielddaylab/penguinsVR#30]
In order to match our conventions for event naming, we should rename `application_start` event to `session_start`, and `begin` to `game_start`.

Note, tying in with issue #29, where we include the random seed in `application_start`, the final result should be:
1. `session_start` : An event which is logged when the game has been initialized, internally assigning a session ID and random seed. If we're still doing the thing where the game resets every time the player takes off their headset, and sets a new session ID, we'd need to log this event (and reset the random seed) every time this happens.  
    * It has `random_seed` as the only item in its `event_data` element.
2. `game_start` : An event which is logged when the game itself starts. If we're using a menu system, it would run when the user starts the a new game from the menu. If we're not doing that anymore, this might be the same time as `session_start`. If we're doing the re-start on headset off/on, but not assigning a new session ID every time, then only `game_start` would need to be logged when that happens, and not `session_start`.  
    * It has `mode` as the only item in its `event_data` element. This should be a string indicating the mode. As best as I recall, we dropped the "event mode" concept, so this can always just be `"HOME_MODE"` or whatever mode is the default one.

**Comment by rossTnick** [comment]
7c7feb65b3209f58b629bcaf5ed91a36c1a7038f
