### ISSUE TITLE
Implement `player_waddle` event

### ISSUE THREAD

**Issue by LswaN58** [fielddaylab/penguinsVR#5]
We previously discussed this in slack, figured we should have it tracked here.

This event should contain:
player position prior to the waddle occurring (e.g. `old_posX`, `old_posY`, `old_posZ`, whatever is consistent with other events), player position and orientation at the moment the waddle completed (e.g. `posX`, `posY`, ..., `rotZ`, `rotW` or whatever is consistent with other events).

**Comment by rossTnick** [comment]
a2313e8e6743d17c6a1f9d548e266cd8a10899e2
