### ISSUE TITLE
Log region name to game_state

### ISSUE THREAD

**Issue by LswaN58** [fielddaylab/penguinsVR#6]

**Comment by LswaN58** [comment]
Forgot to give this a description yesterday;
In `game_state`, we should have a `current_region` element.
When the player is in a region, the region name should be there, and if the player is outside all of our custom-defined regions, it can just be "None" or "Main" or "No Region", whatever makes sense as a default.

**Comment by rossTnick** [comment]
79d12b9b438d64436df10a78b57c48a68188b1cd

**Comment by LswaN58** [comment]
Note: I think changes are in 8e475f754316eb050c2cd510455b2a850e257b2d
