### ISSUE TITLE
Make regions use a buffer zone

### ISSUE THREAD

**Issue by LswaN58** [fielddaylab/penguinsVR#8]
There is an issue where a player standing near the edge of a region can trigger several consecutive enter/exit region events by simply leaning into/out of the region.

Instead of defining one boundary for a region, we should create an inner and outer boundary. When a player enters the inner boundary, the "enter" event should fire, and their `game_state` should include that region as `current_region`. However, the "exit" event should not occur until the player leaves the outer boundary. At that point, their `game_state` can return to `current_region = "No Region"` or `"Main"` or `"None"` or whatever default we decide to use.

**Comment by LswaN58** [comment]
I know we've discussed this before, I never created an issue to ensure we kept track of it; I'm not sure of the current status.

**Comment by rossTnick** [comment]
Made it default to "none"
79d12b9b438d64436df10a78b57c48a68188b1cd

**Comment by LswaN58** [comment]
Note: I think 8e475f754316eb050c2cd510455b2a850e257b2d contains the changes

**Comment by LswaN58** [comment]
There are a couple issues with this implementation:

1. Currently, events are using, for example, `MirrorInner` and `MirrorOuter`, when they should just indicate that the region is `Mirror`
2. It looks like `enter_region` triggers every time the player enters the "inner" part of a region. A new `enter_region` should not trigger until you've left the region (by leaving the "outer" region).
3. To investigate: do regions ever overlap? We have case where player enters `HillUpInner` and then exit `MirrorOuter`, or another case where they enter `SnowballBolwingInner` many times, and then exit `HillDownOuter` multiple.
4. While this slightly breaks conventions, the `enter_region` event should store the newly-entered region in its `game_state`, not the prior region it was in "at the moment the event occurred." Not quite consistent with that convention, but makes sense on its own as this event is the marker of being in that region.

**Comment by rdtredinnick** [comment]
I'll take a look into these and revise.

**Comment by LswaN58** [comment]
Awesome, thanks! Let me know (either here or via Slack) if you need any clarifications; I jotted this list down in a meeting, so it's not quite as detailed or specific as usual.

**Comment by rossTnick** [comment]
3a47667402d7b62a97d311fe9917f10e9d36cd03
